server:
  port: 30000


spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:${record.work-path}/db
  jpa:
    hibernate:
      ddl-auto: update

record:
  check-interval: 30
  work-path: ${user.home}/.bili

logging:
  file:
    path: ${record.work-path}/log/
  logback:
    rollingpolicy:
      max-file-size: 50MB